apiVersion: skaffold/v3
kind: Config
metadata:
  name: swagger
profiles:
  - name: swaglabs-global
    deploy:
      helm:
        releases:
          - name: tests
            chartPath: helm-chart
            namespace: swaglabs-global
            setValueTemplates:
              robotcmd: "Tests"
              dryRun: "false"
  - name: swaglabs-local
    deploy:
      helm:
        releases:
          - name: tests
            chartPath: helm-chart
            namespace: swaglabs-local
            setValueTemplates:
              robotcmd: "Tests"
              dryRun: "false"
